version: "3.9"

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - .env

  finance_web:
    container_name: finance_cont
    build:
      context: .
    volumes:
      - .:/app
    entrypoint: ./wsgi-entrypoint.sh
    depends_on:
      - db
      - redis
    ports:
      - 8080:8080
    networks:
      - my-network
    env_file:
      - .env

  redis:
    container_name: send_mail_redis_nah
    image: redis
    env_file:
      - .env
    networks:
      - my-network

  celery_worker:
    restart: always
    build:
      context: .
    image: django_celery_example_celery_worker
    volumes:
      - .:/app
    entrypoint: ./run-celery.sh
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - redis
      - finance_web

volumes:
  media:
  static:
  postgres_data:

networks:
  my-network:
