# Generated by Django 4.1.3 on 2022-11-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('codename', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Имя кода')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('is_base_expense', models.BooleanField(default=True)),
                ('aliases', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
