# Generated by Django 4.1.3 on 2022-11-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('codename', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Имя кода')),
                ('daily_limit', models.IntegerField(verbose_name='Лимит дня')),
            ],
            options={
                'verbose_name': 'Бюджет',
                'verbose_name_plural': 'Бюджеты',
            },
        ),
    ]
