# Generated by Django 4.1.3 on 2022-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='codename',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Code name'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='daily_limit',
            field=models.IntegerField(verbose_name='Daily limit'),
        ),
    ]
